[package]
name = "dlli"
version = "0.1.0"
edition = "2018"

[dependencies]
kernel32-sys = "0.2.2"
libc = "0.2.102"
user32-sys = "0.2.0"
w32-error = "1.0.0"
winapi = { version = "0.3.9", features = ["winuser", "errhandlingapi"] }
windows = "0.21.0"

[build-dependencies]
windows = "0.21.0"
