[package]
name = "dlli"
version = "0.1.0"
edition = "2018"

[dependencies]
kernel32-sys = "0.2.2"
user32-sys = "0.2.0"
winapi = { version = "0.3.9", features = ["winuser"] }
windows = "0.20.0"

[build-dependencies]
windows = "0.20.0"
